### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by thealamu** [Weirdricc/robofriends#1]
Is there a roadmap? Are you accepting contributions?

**Comment by thealamu** [comment]
Felt cute, might delete later.
Now I feel I'm spamming?

**Comment by thealamu** [comment]
Naah

**Comment by Weirdricc** [comment]
> Is there a roadmap? Are you accepting contributions?

Sure, why not. The more the merrier. I'd also like to see where this can go 😆

**Comment by thealamu** [comment]
Awesome
